https://github.com/stelligent/cfn_nag/issues/463
stelligent/cfn_nag pull request #495
Opened 2020-11-05 16:20 UTC by pethers

2020-11-10 09:40 UTC, pethers commented
@thegonch can you please review this ?

2020-11-23 18:16 UTC, pethers commented
Can anyone at Stelligent please review this ?

2020-11-25 19:35 UTC, arothian approved these changes
Looks good, thanks for the contribution

2020-11-25 20:40 UTC, thegonch requested changes
Looks good, just needs one update to pass rubocop.

2020-11-25 20:40 UTC, thegonch commented on lib/cfn-nag/custom_rules/DynamoDBBackupRule.rb
> +      table.pointInTimeRecoverySpecification.nil? || !truthy?(table.pointInTimeRecoverySpecification['PointInTimeRecoveryEnabled'].to_s)
This line will likely fail rubocop checks due to being too long.  Recommend changing to:

`table.pointInTimeRecoverySpecification.nil? ||`
`  ` `!truthy?(table.pointInTimeRecoverySpecification['PointInTimeRecoveryEnabled'].to_s)`

2020-11-25 21:27 UTC, pethers commented
> Looks good, just needs one update to pass rubocop.

Thanks for the feedback, will fix shortly.

2020-11-25 21:37 UTC, thegonch approved these changes

2020-11-25 21:37 UTC, merged