Lambda inside vpc
stelligent/cfn_nag pull request #527
Opened 2021-02-18 10:42 UTC by pethers

part of https://github.com/stelligent/cfn_nag/issues/503

2021-03-01 20:04 UTC, pethers commented
Can anyone please review this. @arothian

2021-04-01 17:32 UTC, pethers commented
Can somebody please review this !
@thegonch @oshaughnessy

2021-04-02 22:25 UTC, arothian requested changes
Thanks @pethers for the contribution. I added some minor suggestions on rule text/description but this looks good. Thanks!

2021-04-02 22:25 UTC, arothian commented on lib/cfn-nag/custom_rules/LambdaFunctionInsideVPCRule.rb
> +    'Lambda functions should be deployed inside a VPC, miss VpcConfig property'
```suggestion
    'Lambda functions should be deployed inside a VPC'
```

2021-04-02 22:25 UTC, arothian commented on spec/cfn_nag_integration/cfn_nag_lambda_permission_spec.rb
> +                            message: 'Lambda functions should be deployed inside a VPC, miss VpcConfig property',
```suggestion
                            message: 'Lambda functions should be deployed inside a VPC',
```

2021-04-05 13:23 UTC, arothian approved these changes

2021-04-05 13:23 UTC, merged